python train_textgrad.py --dataset_name boolean_expressions --train_size 25 --val_size 25 --epochs 20
python train_textgrad.py --dataset_name causal_judgement --train_size 25 --val_size 25 --epochs 20
python train_textgrad.py --dataset_name coin_flip --train_size 25 --val_size 25 --epochs 20
python train_textgrad.py --dataset_name CommonsenseQA --train_size 25 --val_size 25 --epochs 20
python train_textgrad.py --dataset_name date_understanding --train_size 25 --val_size 25 --epochs 20
python train_textgrad.py --dataset_name disambiguation_qa --train_size 25 --val_size 25 --epochs 20
python train_textgrad.py --dataset_name GSM8K --train_size 25 --val_size 25 --epochs 20
python train_textgrad.py --dataset_name last_letters --train_size 25 --val_size 25 --epochs 20
python train_textgrad.py --dataset_name MultiArith --train_size 25 --val_size 25 --epochs 20
python train_textgrad.py --dataset_name StrategyQA --train_size 25 --val_size 25 --epochs 20
